http_server:
  bind_address: "127.0.0.1"
  bind_port: 9899
urls:
  discord_webhook: "https://discord.com/api/webhooks/example/your-token-here"
  api_endpoint: "https://api.example.com/"
  skin_icons: "https://api.example.com/get_player_icon/%s"